---
title: "Data Analysis Expanded"
author: "Alex Paynter"
date: "August 9, 2019"
output: html_document
---

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, include = T, cache = T, message = F, results = 'hide')
knitr::opts_knit$set(root.dir = here::here("data_analysis"))
```

```{r load_data}
library(magrittr)
library(rre)
library(dplyr)

lakes <- readr::read_tsv("./lakes_data.txt") %>% as.data.frame()
lakes_metadata <- readr::read_tsv("./lakes_metadata.txt") %>% as.data.frame()

# goal is to grab a set of samples from the same year and site
get_samples <- function(yr, zone, per = NULL, month = NULL) {
  quo_period <- dplyr::enquo(per)
  sample_list <- lakes_metadata %>%
    dplyr::filter(Site == zone) %>%
    dplyr::filter(Years == yr)
  if (!is.null(per)) {
    sample_list %<>%  dplyr::filter(Period == per) 
  }
  if (!is.null(month)) {
    sample_list %<>%  dplyr::filter(Months == month) 
  }
  sample_list %<>% dplyr::select(SampleID) %>% unlist
  tables <- lakes[,colnames(lakes) %in% sample_list] %>%
    lapply(., rre::make_frequency_count_table)
  return(tables)
}

report_results_2 <- function(method_output, sample, report_eta = F) {
  best <- method_output[["best"]]
  c_hat <- best$ccc
  m <- c_hat/(rre::get_cc_max(sample))
  out_text <- paste0("C_hat: ", c_hat, "\n\n", 
             round(m,2), " times greater than observed richness \n\nSelected lambda: ", 
             best$selected_lambda, "\n\n")
  if (report_eta) {
    out_text <- paste0(out_text, "alpha = ", best$alpha,
                       ", delta = ", best$delta)
  }
  cat(out_text)
}

# Note that one of the metadata files matches no lakes sample ID:  12.07.11.1
list_of_samples <- mapply(get_samples, seq(2009, 2011), "Littoral", "Summer")

big_starts = data.frame(alpha = c(0.1, 0.01, 0.01, 0.001), 
                        delta = c(0.1, 0.01, 0.0001, 0.001))
```

## Method 0

### Sample 1

```{r s1_m0_a}
s1_m0_a <- rre::unregularized_mle(list_of_samples[[1]], 
                                  multiplier = 200,
                                  c_seq_len = 200,
                                  starts = big_starts)
```
```{r s1_m0_a_print, results = 'asis'}
report_results_2(s1_m0_a, list_of_samples[[1]], report_eta = T)
```
<br>
<br>


```{r s1_m0_b}
# Use a very dense C grid, see if previous result is stable:
s1_m0_b <- rre::unregularized_mle(list_of_samples[[1]], 
                                  multiplier = 200,
                                  c_seq_len = 1000,
                                  starts = data.frame(alpha = 0.0008818,
                                           delta = 0.001802))
```
```{r s1_m0_b_print, results = 'asis'}
report_results_2(s1_m0_b, list_of_samples[[1]], report_eta = T)
```
<br>
<br>

### Sample 2

```{r s2_m0_a}
s2_m0_a <- rre::unregularized_mle(list_of_samples[[2]], 
                                  multiplier = 200,
                                  c_seq_len = 200,
                                  starts = big_starts)
```
```{r s2_m0_a_print, results = 'asis'}
report_results_2(s2_m0_a,  list_of_samples[[2]], report_eta = T)
```
<br>
<br>

```{r s2_m0_b}
# Use a very dense C grid, see if previous result is stable:
s2_m0_b <- rre::unregularized_mle(list_of_samples[[2]], 
                                  multiplier = 200,
                                  c_seq_len = 1000,
                                  starts = data.frame(alpha = 0.001846,
                                                      delta = 0.002530))
```
```{r s2_m0_b_print, results = 'asis'}
report_results_2(s2_m0_b,  list_of_samples[[2]], report_eta = T)
```
<br>
<br>

### Sample 3

```{r s3_m0_a}
s3_m0_a <- rre::unregularized_mle(list_of_samples[[3]],
                                  multiplier = 200,
                                  c_seq_len = 200,
                                  starts = big_starts)
```
```{r s3_m0_a_print, results = 'asis'}
report_results_2(s3_m0_a, list_of_samples[[3]], report_eta = T)
```
<br>
<br>

```{r s3_m0_b}
# Use a very dense C grid, see if previous result is stable:
s3_m0_b <- rre::unregularized_mle(list_of_samples[[3]],
                                  multiplier = 200,
                                  c_seq_len = 1000,
                                  starts = data.frame(alpha = 0.001606,
                                                      delta = 0.001396))
```
```{r s3_m0_b_print, results = 'asis'}
report_results_2(s3_m0_b, list_of_samples[[3]], report_eta = T)
```
<br>
<br>

<br><br>

## Method 1

### Sample 1

```{r s1_m1_a}
# big grids and few partitions to start:
set.seed(12039)
s1_m1_a <- rre::minimum_subset_distance(list_of_samples[[1]],
                                        partitions = 5,
                                        lambda_vec = seq(0,1000,by=200),
                                        multiplier = 100,
                                        c_seq_len = 20)
```
```{r s1_m1_a_print, results = 'asis'}
s1_m1_a %>% report_results_2(., list_of_samples[[1]], report_eta = T)
```
<br><br>

```{r s1_m1_b}
# more starts, lambda refinement, smaller multiplier:
set.seed(12439)
s1_m1_b <- rre::minimum_subset_distance(list_of_samples[[1]],
                                        partitions = 5,
                                        lambda_vec = seq(400,800, by = 50),
                                        multiplier = 20,
                                        c_seq_len = 50, # mean to to do 50 here last time, and did not.
                                        starts = big_starts)
```
```{r s1_m1_b_print, results = 'asis'}
s1_m1_b %>% report_results_2(.,  list_of_samples[[1]], report_eta = T)
```
<br><br>

```{r s1_m1_c}
# lambda refinement, see if the result is stable, full partitions:
set.seed(12439)
s1_m1_c <- rre::minimum_subset_distance(list_of_samples[[1]],
                                        partitions = 10,
                                        lambda_vec = seq(650, 750, by = 5),
                                        multiplier = 10,
                                        c_seq_len = 100,
                                        starts = data.frame(alpha = 0.3463,
                                                            delta = 0.003673))
```
```{r s1_m1_c_print, results = 'asis'}
s1_m1_c %>% report_results_2(.,  list_of_samples[[1]], report_eta = T)
```
<br><br>

```{r s1_m1_d}

set.seed(2339)
s1_m1_d <- rre::minimum_subset_distance(list_of_samples[[1]],
                                        partitions = 10,
                                        lambda_vec = 700:740,
                                        multiplier = 2,
                                        c_seq_len = 11,
                                        starts = data.frame(alpha = 0.28863,
                                                            delta = 0.0032607))
```
```{r s1_m1_d_print, results = 'asis'}
s1_m1_d %>% report_results_2(.,  list_of_samples[[1]], report_eta = T)
```
<br><br>


<br><br>

### Sample 2

```{r s2_m1_a}
# big grids and few partitions to start:
set.seed(2345629)
s2_m1_a <- rre::minimum_subset_distance(list_of_samples[[2]],
                                        partitions = 5,
                                        lambda_vec = seq(0,1000,by=200),
                                        multiplier = 100,
                                        c_seq_len = 50)
```
```{r s2_m1_a_print, results = 'asis'}
s2_m1_a %>% report_results_2(., list_of_samples[[2]])
```
<br><br>

```{r s2_m1_b}
# more starts, lambda refinement, smaller multiplier:
set.seed(239)
s2_m1_b <- rre::minimum_subset_distance(list_of_samples[[2]],
                                        partitions = 5,
                                        lambda_vec = seq(400,800,by = 50),
                                        multiplier = 20,
                                        c_seq_len = 50,
                                        starts = big_starts)
```
```{r s2_m1_b_print, results = 'asis'}
s2_m1_b %>% report_results_2(., list_of_samples[[2]], report_eta = T)
```
<br><br>

```{r s2_m1_c}
set.seed(239234)
s2_m1_c <- rre::minimum_subset_distance(list_of_samples[[2]],
                                        partitions = 10,
                                        lambda_vec = seq(450,550,by=5),
                                        multiplier = 2,
                                        c_seq_len = 11,
                                        starts = data.frame(alpha = 0.56337,
                                                            delta = 0.0067572))
```
```{r s2_m1_c_print, results = 'asis'}
s2_m1_c %>% report_results_2(., list_of_samples[[2]], report_eta = T)
```
<br><br>

<br><br>

### Sample 3

```{r s3_m1_a}
# big grids and few partitions to start:
set.seed(45698)
s3_m1_a <- rre::minimum_subset_distance(list_of_samples[[3]],
                                        partitions = 5,
                                        lambda_vec = seq(0,1000,by=200),
                                        multiplier = 100,
                                        c_seq_len = 50)
```
```{r s3_m1_a_print, results = 'asis'}
s3_m1_a %>% report_results_2(., list_of_samples[[3]])
```
<br><br>

```{r s3_m1_b}
# more starts, lambda refinement, smaller multiplier:
set.seed(45698)
s3_m1_b <- rre::minimum_subset_distance(list_of_samples[[3]],
                                        partitions = 5,
                                        lambda_vec = seq(200,600,by=50),
                                        multiplier = 20,
                                        c_seq_len = 50,
                                        starts = big_starts)
```
```{r s3_m1_b_print, results = 'asis'}
s3_m1_b %>% report_results_2(., list_of_samples[[3]], report_eta = T)
```
<br><br>

```{r s3_m1_c}
# refine lambda, full partitions, see if the previous result is stable:
set.seed(45698)
s3_m1_c <- rre::minimum_subset_distance(list_of_samples[[3]],
                                        partitions = 10,
                                        lambda_vec = seq(500, 600 ,by=5),
                                        multiplier = 10,
                                        c_seq_len = 100,
                                        starts = data.frame(alpha = 0.4392,
                                                            delta = 0.003637))
```
```{r s3_m1_c_print, results = 'asis'}
s3_m1_c %>% report_results_2(., list_of_samples[[3]], report_eta = T)
```
<br><br>

```{r s3_m1_d}
set.seed(452348)
s3_m1_d <- rre::minimum_subset_distance(list_of_samples[[3]],
                                        partitions = 10,
                                        lambda_vec = seq(500, 600 ,by=5),
                                        multiplier = 2,
                                        c_seq_len = 11,
                                        starts = data.frame(alpha = 0.5143,
                                                            delta = 0.003997))
```
```{r s3_m1_d_print, results = 'asis'}
s3_m1_d %>% report_results_2(., list_of_samples[[3]], report_eta = T)
```
<br><br>

<br><br>

## Method 2

### Sample 1

```{r s1_m2_a}
# big grids and few partitions to start:
set.seed(12039)
s1_m2_a <- rre::cv_replicates(list_of_samples[[1]],
                              eval_function = "neg_unreg_like",
                              partitions = 5,
                              lambda_vec = seq(0,1000,by=200),
                              multiplier = 200,
                              c_seq_len = 20)
```
```{r s1_m2_a_print, results = 'asis'}
s1_m2_a %>% report_results_2(., list_of_samples[[1]])
```
<br><br>


```{r s1_m2_b}
# narrow lambda, more starts:
set.seed(12039)
s1_m2_b <- rre::cv_replicates(list_of_samples[[1]],
                              eval_function = "neg_unreg_like",
                              partitions = 5,
                              lambda_vec = seq(0,300,by=20),
                              multiplier = 200,
                              c_seq_len = 20,
                              starts = big_starts)
```
```{r s1_m2_b_print, results = 'asis'}
s1_m2_b %>% report_results_2(., list_of_samples[[1]], report_eta = T)
```
<br><br>

```{r s1_m2_c}
set.seed(4439)
s1_m2_c <- rre::cv_replicates(list_of_samples[[1]],
                              eval_function = "neg_unreg_like",
                              partitions = 5,
                              lambda_vec = seq(150,250,by=5),
                              multiplier = 200,
                              c_seq_len = 200,
                              starts = data.frame(alpha = 0.001879,
                                                  delta = 0.002208))
```
```{r s1_m2_c_print, results = 'asis'}
s1_m2_c %>% report_results_2(., list_of_samples[[1]], report_eta = T)
```
<br><br>

### Sample 2

```{r s2_m2_a}
# big grids and few partitions to start:
set.seed(120239)
s2_m2_a <- rre::cv_replicates(list_of_samples[[2]],
                              eval_function = "neg_unreg_like",
                              partitions = 5,
                              lambda_vec = seq(0,1000,by=200),
                              multiplier = 200,
                              c_seq_len = 20)
```
```{r s2_m2_a_print, results = 'asis'}
s2_m2_a %>% report_results_2(., list_of_samples[[2]])
```
<br><br>

```{r s2_m2_b}
# narrow lambda, more starts:
set.seed(12039)
s2_m2_b <- rre::cv_replicates(list_of_samples[[2]],
                              eval_function = "neg_unreg_like",
                              partitions = 5,
                              lambda_vec = seq(0,300,by=20),
                              multiplier = 200,
                              c_seq_len = 20,
                              starts = big_starts)
```
```{r s2_m2_b_print, results = 'asis'}
s2_m2_b %>% report_results_2(., list_of_samples[[2]], report_eta = T)
```
<br><br>

```{r s2_m2_c}
# narrow lambda, more starts:
set.seed(12044)
s2_m2_c <- rre::cv_replicates(list_of_samples[[2]],
                              eval_function = "neg_unreg_like",
                              partitions = 5,
                              lambda_vec = seq(0,100,by=5),
                              multiplier = 200,
                              c_seq_len = 200,
                              starts = data.frame(alpha = 0.002191,
                                                  delta = 0.002789))
```
```{r s2_m2_c_print, results = 'asis'}
s2_m2_c %>% report_results_2(., list_of_samples[[2]], report_eta = T)
```
<br><br>

### Sample 3

```{r s3_m2_a}
# big grids and few partitions to start:
set.seed(223439)
s3_m2_a <- rre::cv_replicates(list_of_samples[[3]],
                              eval_function = "neg_unreg_like",
                              partitions = 5,
                              lambda_vec = seq(0,1000,by=200),
                              multiplier = 200,
                              c_seq_len = 20)
```
```{r s3_m2_a_print, results = 'asis'}
s3_m2_a %>% report_results_2(., list_of_samples[[3]])
```
<br><br>

```{r s3_m2_b}
# narrow lambda, more starts:
set.seed(23439)
s3_m2_b <- rre::cv_replicates(list_of_samples[[3]],
                              eval_function = "neg_unreg_like",
                              partitions = 5,
                              lambda_vec = seq(0,300,by=20),
                              multiplier = 200,
                              c_seq_len = 20,
                              starts = big_starts)
```
```{r s3_m2_b_print, results = 'asis'}
s3_m2_b %>% report_results_2(., list_of_samples[[3]], report_eta = T)
```
<br><br>

```{r s3_m2_c}
# narrow lambda, more starts:
set.seed(23444)
s3_m2_c <- rre::cv_replicates(list_of_samples[[3]],
                              eval_function = "neg_unreg_like",
                              partitions = 5,
                              lambda_vec = seq(0,100,by=5),
                              multiplier = 200,
                              c_seq_len = 200,
                              starts = data.frame(alpha = 0.005138,
                                                  delta = 0.002135))
```
```{r s3_m2_c_print, results = 'asis'}
s3_m2_c %>% report_results_2(., list_of_samples[[3]], report_eta = T)
```
<br><br>

_Note_ The 'c' round of method 2 took over a day to run for these 3 samples.

<br><br>

## Method 3

### Sample 1

```{r s1_m3_a}
s1_m3_a <- rre::gof_criterion(list_of_samples[[1]], 
                              lambda_vec = seq(0,1000,by=100),
                              multiplier = 200,
                              c_seq_len = 10)
```
```{r s1_m3_a_print, results = 'asis'}
s1_m3_a %>% report_results_2(., list_of_samples[[1]])
```
<br>
<br>


```{r s1_m3_b}
# Zero in on lambda, use a more dense C grid:
s1_m3_b <- rre::gof_criterion(list_of_samples[[1]], 
                              lambda_vec = seq(300,500,by=10),
                              multiplier = 200,
                              c_seq_len = 20)
```
```{r s1_m3_b_print, results = 'asis'}
s1_m3_b %>% report_results_2(., list_of_samples[[1]])
```
<br>
<br>

```{r s1_m3_c}
s1_m3_c <- rre::gof_criterion(list_of_samples[[1]], 
                              lambda_vec = seq(450,530,by=5),
                              multiplier = 200,
                              c_seq_len = 50,
                              starts = big_starts)
```
```{r s1_m3_c_print, results = 'asis'}
s1_m3_c %>% report_results_2(., list_of_samples[[1]], report_eta = T)
```
<br>
<br>

```{r s1_m3_d}
s1_m3_d <- rre::gof_criterion(list_of_samples[[1]],
                             lambda_vec = seq(500,650,by=10),
                             multiplier = 200,
                             c_seq_len = 200,
                             starts = data.frame(alpha = 0.001738,
                                                 delta = 0.001744))
```
```{r s1_m3_d_print, results = 'asis'}
s1_m3_d %>% report_results_2(., list_of_samples[[1]], report_eta = T)
```
<br><br>
<br><br>

### Sample 2
```{r s2_m3_a}
s2_m3_a <- rre::gof_criterion(list_of_samples[[2]], 
                              lambda_vec = seq(0,1000,by=100),
                              multiplier = 200,
                              c_seq_len = 10)
```
```{r s2_m3_a_print, results = 'asis'}
s2_m3_a %>% report_results_2(., list_of_samples[[2]])
```
<br>
<br>

```{r s2_m3_b}
# Zero in on lambda, use a more dense C grid:
s2_m3_b <- rre::gof_criterion(list_of_samples[[2]], 
                              lambda_vec = seq(0,200,by=10),
                              multiplier = 200,
                              c_seq_len = 20)
```
```{r s2_m3_b_print, results = 'asis'}
s2_m3_b %>% report_results_2(., list_of_samples[[2]])
```
<br>
<br>

```{r s2_m3_c}
# Zero in on lambda, use a more dense C grid:
s2_m3_c <- rre::gof_criterion(list_of_samples[[2]], 
                              lambda_vec = seq(120,200,by=5),
                              multiplier = 200,
                              c_seq_len = 50)
```
```{r s2_m3_c_print, results = 'asis'}
s2_m3_c %>% report_results_2(., list_of_samples[[2]])
```
<br>
<br>

```{r s2_m3_d}
# Selected lambda was on the edge of previous grid, lets try again:
s2_m3_d <- rre::gof_criterion(list_of_samples[[2]], 
                              lambda_vec = seq(150,300,by=10),
                              multiplier = 100,
                              c_seq_len = 50,
                              starts = big_starts)
```
```{r s2_m3_d_print, results = 'asis'}
s2_m3_d %>% report_results_2(., list_of_samples[[2]], report_eta =T)
```
<br><br>

```{r s2_m3_e}
# Selected lambda was on the edge of previous grid, lets try again:
s2_m3_e <- rre::gof_criterion(list_of_samples[[2]],
                             lambda_vec = seq(150,300,by=10),
                             multiplier = 100,
                             c_seq_len = 100,
                             starts = data.frame(alpha = 0.004656,
                                                 delta = 0.0025668))
```
```{r s2_m3_e_print, results = 'asis'}
s2_m3_e %>% report_results_2(., list_of_samples[[2]], report_eta =T)
```
<br><br>
<br><br>

### Sample 3
```{r s3_m3_a}
s3_m3_a <- rre::gof_criterion(list_of_samples[[3]], 
                              lambda_vec = seq(0,1000,by=100),
                              multiplier = 200,
                              c_seq_len = 10)
```
```{r s3_m3_a_print, results = 'asis'}
s3_m3_a %>% report_results_2(., list_of_samples[[3]])
```
<br>
<br>

```{r s3_m3_b}
# Zero in on lambda, use a more dense C grid:
s3_m3_b <- rre::gof_criterion(list_of_samples[[3]], 
                              lambda_vec = seq(0,100,by=10),
                              multiplier = 200,
                              c_seq_len = 20)
```
```{r s3_m3_b_print, results = 'asis'}
s3_m3_b %>% report_results_2(., list_of_samples[[3]])
```
<br>
<br>


```{r s3_m3_c}
s3_m3_c <- rre::gof_criterion(list_of_samples[[3]], 
                              lambda_vec = seq(50,130,by=10),
                              multiplier = 200,
                              c_seq_len = 50)
```
```{r s3_m3_c_print, results = 'asis'}
s3_m3_c %>% report_results_2(., list_of_samples[[3]])
```
<br>
<br>

```{r s3_m3_d}
# Selected lambda was on the edge of previous grid, lets try again:
s3_m3_d <- rre::gof_criterion(list_of_samples[[3]], 
                              lambda_vec = seq(100, 200, by=10),
                              multiplier = 100,
                              c_seq_len = 50,
                              starts = big_starts)
```
```{r s3_m3_d_print, results = 'asis'}
s3_m3_d %>% report_results_2(., list_of_samples[[3]], report_eta = T)
```
<br><br>


```{r s3_m3_e}
# Selected lambda was on the edge of previous grid, lets try again:
s3_m3_e <- rre::gof_criterion(list_of_samples[[3]],
                             lambda_vec = seq(150, 250, by=10),
                             multiplier = 100,
                             c_seq_len = 100,
                             starts = data.frame(alpha = 0.0014137,
                                                delta = 0.001367))
```
```{r s3_m3_e_print, results = 'asis'}
s3_m3_e %>% report_results_2(., list_of_samples[[3]], report_eta = T)
```
<br><br><br><br>


## Method 4

### Sample 1

```{r s1_m4_a}
# big grids and few partitions to start:
set.seed(87124)
s1_m4_a <- rre::cv_replicates(list_of_samples[[1]],
                              eval_function = "gof_chi_sq",
                              partitions = 5,
                              lambda_vec = seq(0,1000,by=200),
                              multiplier = 200,
                              c_seq_len = 20)
```
```{r s1_m4_a_print, results = 'asis'}
s1_m4_a %>% report_results_2(., list_of_samples[[1]])
```

<br><br>


```{r s1_m4_b}
set.seed(24)
s1_m4_b <- rre::cv_replicates(list_of_samples[[2]],
                              eval_function = "gof_chi_sq",
                              partitions = 5,
                              lambda_vec = seq(0,300,by=20),
                              multiplier = 200,
                              c_seq_len = 50,
                              starts = big_starts)
```
```{r s1_m4_b_print, results = 'asis'}
s1_m4_b %>% report_results_2(., list_of_samples[[1]], report_eta = T)
```

<br><br>

```{r s1_m4_c}
set.seed(2423)
s1_m4_c <- rre::cv_replicates(list_of_samples[[2]],
                              eval_function = "gof_chi_sq",
                              partitions = 5,
                              lambda_vec = seq(50,150,by=5),
                              multiplier = 200,
                              c_seq_len = 200,
                              starts = data.frame(alpha = 0.005779,
                                                  delta = 0.002530))
```
```{r s1_m4_c_print, results = 'asis'}
s1_m4_c %>% report_results_2(., list_of_samples[[1]], report_eta = T)
```

<br><br>


### Sample 2

```{r s2_m4_a}
# big grids and few partitions to start:
set.seed(23456)
s2_m4_a <- rre::cv_replicates(list_of_samples[[2]],
                              eval_function = "gof_chi_sq",
                              partitions = 5,
                              lambda_vec = seq(0,1000,by=200),
                              multiplier = 200,
                              c_seq_len = 20)
```
```{r s2_m4_a_print, results = 'asis'}
s2_m4_a %>% report_results_2(., list_of_samples[[2]])
```

<br><br>

```{r s2_m4_b}
set.seed(2345)
s2_m4_b <- rre::cv_replicates(list_of_samples[[2]],
                              eval_function = "gof_chi_sq",
                              partitions = 5,
                              lambda_vec = seq(0,200,by=20),
                              multiplier = 200,
                              c_seq_len = 50,
                              starts = big_starts)
```
```{r s2_m4_b_print, results = 'asis'}
s2_m4_b%>% report_results_2(., list_of_samples[[2]], report_eta = T)
```

<br><br>

```{r s2_m4_c}
set.seed(23451)
s2_m4_c <- rre::cv_replicates(list_of_samples[[2]],
                              eval_function = "gof_chi_sq",
                              partitions = 5,
                              lambda_vec = seq(0,100,by=5),
                              multiplier = 200,
                              c_seq_len = 200,
                              starts = data.frame(alpha = 0.0016934,
                                                  delta = 0.0027209))
```
```{r s2_m4_c_print, results = 'asis'}
s2_m4_c%>% report_results_2(., list_of_samples[[2]], report_eta = T)
```

<br><br>

### Sample 3
```{r s3_m4_a}
# big grids and few partitions to start:
set.seed(7654)
s3_m4_a <- rre::cv_replicates(list_of_samples[[3]],
                              eval_function = "gof_chi_sq",
                              partitions = 5,
                              lambda_vec = seq(0,1000,by=200),
                              multiplier = 200,
                              c_seq_len = 20)
```
```{r s3_m4_a_print, results = 'asis'}
s3_m4_a %>% report_results_2(., list_of_samples[[3]])
```

<br><br>

```{r s3_m4_b}
# big grids and few partitions to start:
set.seed(7654)
s3_m4_b <- rre::cv_replicates(list_of_samples[[3]],
                              eval_function = "gof_chi_sq",
                              partitions = 5,
                              lambda_vec = seq(0,200,by=20),
                              multiplier = 200,
                              c_seq_len = 50,
                              starts = big_starts)
```
```{r s3_m4_b_print, results = 'asis'}
s3_m4_b %>% report_results_2(., list_of_samples[[3]], report_eta = T)
```

<br><br>

```{r s3_m4_c}
# big grids and few partitions to start:
set.seed(7654)
s3_m4_c <- rre::cv_replicates(list_of_samples[[3]],
                              eval_function = "gof_chi_sq",
                              partitions = 5,
                              lambda_vec = seq(0,120,by=5),
                              multiplier = 200,
                              c_seq_len = 200,
                              starts = data.frame(alpha = 0.002450,
                                                  delta = 0.001773))
```
```{r s3_m4_c_print, results = 'asis'}
s3_m4_c %>% report_results_2(., list_of_samples[[3]], report_eta = T)
```

<br><br>
<br><br>

## Output data

For each method and sample we save the most refined or best estimate.
```{r output_data}
sample_1 <- list(method_0 = s1_m0_b$best,
                 method_1 = s1_m1_d$best,
                 method_2 = s1_m2_c$best,
                 method_3 = s1_m3_c$best,
                 method_4 = s1_m4_c$best)

sample_2 <- list(method_0 = s2_m0_b$best,
                 method_1 = s2_m1_c$best,
                 method_2 = s2_m2_c$best,
                 method_3 = s2_m3_d$best,
                 method_4 = s2_m4_c$best)

sample_3 <- list(method_0 = s3_m0_b$best,
                 method_1 = s3_m1_d$best,
                 method_2 = s3_m2_c$best,
                 method_3 = s3_m3_d$best,
                 method_4 = s3_m4_c$best)

sample_outputs <- list(sample_1 = sample_1, 
                       sample_2 = sample_2, 
                       sample_3 = sample_3)

save(sample_outputs, file = "data_analysis_expanded_results.RData")

```