install.packages("devtools")
install.packages("tidyverse")
install.packages("stringr")
install.packages("magrittr")
devtools::install_github("jacobbien/simulator")
devtools::install_github("statdivlab/rre")